[SERVICE]
    Flush                     1
    Daemon                    Off
    Log_Level                 info

    Parsers_File              parsers.conf
    Plugins_File              plugins.conf

    HTTP_Server               off
    HTTP_Listen               0.0.0.0
    HTTP_Port                 2020
    
    Storage.path              C:\fluent-bit\storage
    Storage.sync              normal
    Storage.checksum          Off
    Storage.backlog.mem_limit 100M

###############################################################################
# SECURITY
###############################################################################

[INPUT]
    Name         winlog
    Channels     Security
    DB           C:\fluent-bit\db\security.db
    Interval_Sec 1
    Tag          windows.security

###############################################################################
# SYSTEM
###############################################################################

[INPUT]
    Name         winlog
    Channels     System
    DB           C:\fluent-bit\db\system.db
    Interval_Sec 1
    Tag          windows.system

###############################################################################
# APPLICATION
###############################################################################

[INPUT]
    Name         winlog
    Channels     Application
    DB           C:\fluent-bit\db\application.db
    Interval_Sec 1
    Tag          windows.application

###############################################################################
# FILTERS
###############################################################################

[FILTER]
    Name   modify
    Match  windows.*
    Add    hostname ${COMPUTERNAME}

[FILTER]
    Name   modify
    Match  windows.*
    Add    source windows

[FILTER]
    Name   modify
    Match  windows.*
    Add    event_source windows_eventlog

[FILTER]
    Name   modify
    Match  windows.*
    Add    event_type windows
	
	

###############################################################################
# DEBUG (MANTER DURANTE A IMPLANTAÇÃO)
###############################################################################

[OUTPUT]
    Name   stdout
    Match  windows.*

###############################################################################
# DATA PREPPER
###############################################################################

[OUTPUT]
    Name                     http
    Match                    windows.*
    Host                     192.168.15.200
    Port                     2021
    URI                      /log/ingest
    Format                   json
    #Json_date_key           false
    #Json_date_format        iso8601
    #Json_array              On
    #Compress               Off